-- AlterTable
ALTER TABLE "Route" ADD COLUMN     "distance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "status" "RideStatus" NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "fuelSaved" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "ridesOffered" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ridesTaken" INTEGER NOT NULL DEFAULT 0;
